import './Container1Data.css';

function Container1Data (){
    return (
        <div className="container1Data-container">
            <h1><font size="6">Inventary</font></h1>
        <div id="main-container1">
        <table>
            <thead className="thead">
                <tr>
                    <th>Item</th><th>Brand</th><th>Name</th><th>Acquisition Date</th><th>Value</th><th>Supplier</th>
                    <th>Annual Depreciation</th><th>Montly Depreciation</th><th>Status</th><th>Observation</th><th>Insured</th>
                </tr>
            </thead>
        
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>

            
        </table>
        </div>
        </div>
    );
}
export default Container1Data