import './Container2Data.css';

const Container2Data = () =>{
    return (
        <div className="container1Data-container">
            <center><h1><font size="6">Inventary</font></h1></center>
        <div id="main-container">
        <table className="table1">
            <thead className="thead">
                <tr>
                    <th>Item</th><th>Brand</th><th>Name</th><th>Acquisition Date</th><th>Value</th><th>Supplier</th>
                    <th>Annual Depreciation</th><th>Montly Depreciation</th><th>Status</th><th>Observation</th><th>Insured</th>
                </tr>
            </thead>
        
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>

            
        </table><br/><br/>
        </div>

        <div id="main-container2">
        <table className="table2">
            <tr>
                <th>Item</th><th>Data1</th>
            </tr>
            <tr>
                <td>Marca</td><td>Data2</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data3</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data4</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data5</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data6</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data7</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data8</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data9</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data10</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data11</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data12</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data13</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data14</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data15</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data16</td>
            </tr>
            <tr>
                <td>Marca</td><td>Data17</td>
            </tr>
        </table>
        </div>


        </div>
    );
}
export default Container2Data