import './Container1Data.css';

function Container1Data (){
    return (
        <div className="container1Data-container">
            <center><h1><font size="6">Inventary</font></h1></center>
        <div id="main-container1">
        <table>
            <thead className="thead">
                <tr>
                    <th>Ítem</th><th>Marca</th><th>Nombre</th><th>Fecha de Adquisición</th><th>Valor</th><th>Proveedor</th>
                    <th>Depresiación anual</th><th>Depresiación mensual</th><th>Estado</th><th>Observación</th><th>Asegurado</th>
                </tr>
            </thead>
        
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>
            <tr>
                <td>Data1</td><td>Data2</td><td>Data3</td><td>Data4</td><td>Data5</td>
                <td>Data6</td><td>Data7</td><td>Data8</td><td>Data9</td>
                <td>Data10</td><td>Data11</td>
            </tr>

            
        </table>
        </div>
        </div>
    );
}
export default Container1Data